import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  textHeader: {
    fontSize: 20,
    marginTop: 15,
    marginLeft: 15,
    color: 'black',
    fontFamily: 'Mulish-Bold',
  },
  textType1: {
    fontSize: 20,
    marginTop: 15,
    marginLeft: 15,
    color: 'black',
    borderBottomWidth: 1,
    borderBottomColor: '#5F2EEA',
    fontFamily: 'Mulish-Regular',
  },
  textType2: {
    fontSize: 20,
    marginTop: 15,
    marginLeft: 15,
    color: 'grey',
    fontFamily: 'Mulish-Regular',
  },
  textType3: {
    textAlign: 'left',
    fontSize: 14,
    marginTop: 15,
    marginLeft: 15,
    color: 'grey',
    fontFamily: 'Mulish-Regular',
  },
  textProfile: {
    fontFamily: 'Mulish-bold',
    fontSize: 14,
  },
  textProfile2: {
    fontFamily: 'Mulish-bold',
    fontSize: 14,
    color: 'red',
  },
  textUpload: {
    fontFamily: 'Mulish-bold',
    marginBottom: 10,
    fontSize: 14,
    color: '#5F2EEA',
  },
  buttonUpload: {
    width: 50,
    borderWidth: 1,
    alignItems: 'center',
    borderRadius: 5,
  },
  buttonUpload2: {
    width: 150,
    borderWidth: 1,
    borderColor: '#5F2EEA',
    marginBottom: 4,
    alignItems: 'center',
    borderRadius: 3,
  },
  buttonUpload3: {
    width: 50,
    borderColor: 'red',
    borderWidth: 1,
    alignItems: 'center',
    borderRadius: 5,
  },
  layoutMenuProfile: {
    backgroundColor: 'white',
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 10,
  },
  cardProfile: {
    marginLeft: 20,
    marginTop: 30,
    paddingTop: 20,
    marginBottom: 50,
    height: 430,
    borderRadius: 10,
    backgroundColor: 'white',
    width: '90%',
    alignItems: 'center',
  },
  photo: {
    marginTop: 20,
    marginBottom: 10,
    width: 100,
    height: 100,
    borderRadius: 50,
  },
  logout: {
    width: '50%',
    backgroundColor: '#5F2EEA',
    marginLeft: 20,
    marginTop: 20,
    height: 50,
    paddingTop: 10,
    alignItems: 'center',
    marginBottom: 50,
    borderRadius: 15,
  },
  cardPersonal: {
    marginLeft: 20,
    marginTop: 30,
    marginBottom: 50,
    height: 400,
    borderRadius: 10,
    backgroundColor: 'white',
    width: '90%',
    alignItems: 'center',
  },
  input: {
    marginTop: 10,
    paddingLeft: 30,
    width: '90%',
    borderWidth: 1,
    height: 40,
    borderRadius: 8,
  },
  button: {
    width: '90%',
    backgroundColor: '#5F2EEA',
    marginLeft: 20,
    height: 50,
    paddingTop: 10,
    alignItems: 'center',
    marginBottom: 50,
    borderRadius: 15,
  },
  textButton: {
    color: 'white',
    fontFamily: 'Mulish-Regular',
  },
  warning: {
    marginTop: 30,
    color: 'red',
  },
});
