import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  main: {
    backgroundColor: 'white',
  },
  textMotto1: {
    marginTop: 50,
    marginLeft: 30,
    fontSize: 15,
    fontFamily: 'Mulish-Regular',
    color: '#A0A3BD',
  },
  textMotto2: {
    marginTop: 10,
    marginLeft: 30,
    fontSize: 40,
    fontFamily: 'Mulish-Bold',
    color: '#5F2EEA',
  },
  logo: {
    marginTop: 20,
    width: '100%',
    height: 400,
    resizeMode: 'stretch',
    marginBottom: 100,
  },
  layoutMenu: {
    paddingTop: 50,
    paddingLeft: 20,
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 10,
  },
  menu1: {
    backgroundColor: '#D6D8E7',
    height: 500,
  },
  menu2: {
    backgroundColor: 'white',
    height: 500,
  },
  textMenu: {
    color: '#5F2EEA',
    fontFamily: 'Mulish-Bold',
  },
  layoutMenu2: {
    paddingTop: 50,
    paddingLeft: 20,
    backgroundColor: 'white',
    marginBottom: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 10,
  },
  cardMovie: {
    padding: 10,
    marginTop: 30,
    backgroundColor: '#D6D8E7',
    height: 300,
    width: 150,
    marginRight: 10,
    borderWidth: 1,
    borderColor: '#FFFFFF',
    borderRadius: 6,
    alignItems: 'center',
  },
  movieList: {
    overflow: 'scroll',
    flexDirection: 'row',
    paddingLeft: 20,
  },
  movieImage: {
    width: '100%',
    height: '70%',
  },
  textCard: {
    fontSize: 13,
    fontFamily: 'Mulish-Bold',
  },
  textCard2: {
    fontSize: 11,
    fontFamily: 'Mulish-Regular',
  },
  buttonCard: {
    marginTop: 10,
    borderWidth: 1,
    width: '80%',
    alignItems: 'center',
    borderRadius: 10,
    borderColor: '#5F2EEA',
  },
  buttonMonth: {
    marginLeft: 20,
    width: 100,
    borderWidth: 1,
    height: 30,
    alignItems: 'center',
    borderColor: '#5F2EEA',
    borderRadius: 5,
  },
  buttonTextMonth: {
    color: '#5F2EEA',
    fontFamily: 'Mulish-Regular',
  },
  buttonMonthActive: {
    marginLeft: 20,
    width: 100,
    borderWidth: 1,
    height: 30,
    alignItems: 'center',
    borderColor: '#5F2EEA',
    borderRadius: 5,
    backgroundColor: '#5F2EEA',
  },
  buttonTextMonthActive: {
    color: '#FFFF',
    fontFamily: 'Mulish-Regular',
  },
  cardMovie2: {
    padding: 10,
    marginTop: 30,
    backgroundColor: '#FFFFF',
    height: 300,
    width: 150,
    marginRight: 10,
    borderWidth: 1,
    borderColor: '#D6D8E7',
    borderRadius: 6,
    alignItems: 'center',
  },
  comment: {
    alignItems: 'center',
    height: 350,
    width: '90%',
    marginLeft: 20,
    paddingTop: 30,
  },
  commentTitle1: {
    fontFamily: 'Mulish-Regular',
    fontSize: 16,
  },
  commentTitle2: {
    fontFamily: 'Mulish-Bold',
    fontSize: 35,
    color: '#5F2EEA',
  },
  commentform: {
    borderWidth: 1,
    width: '90%',
    marginTop: 20,
    fontFamily: 'Mulish-Regular',
    paddingLeft: 20,
    borderRadius: 10,
  },
  commentbutton: {
    width: '90%',
    alignItems: 'center',
    paddingTop: 10,
    backgroundColor: '#5F2EEA',
    marginTop: 20,
    height: 50,
    borderRadius: 10,
  },
  commentbuttontext: {
    color: 'white',
    fontFamily: 'Mulish-Bold',
  },
  commentTitle3: {
    marginTop: 20,
    fontFamily: 'Mulish-Regular',
    fontSize: 15,
    width: '80%',
    textAlign: 'center',
  },
});
