import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  menu1: {
    backgroundColor: 'white',
  },
  menu2: {
    backgroundColor: '#F5F6F8',
    alignItems: 'center',
  },
  textHeader: {
    fontSize: 20,
    marginTop: 15,
    marginLeft: 15,
    color: 'black',
    fontFamily: 'Mulish-Bold',
  },
  textType1: {
    fontSize: 20,
    marginTop: 15,
    marginLeft: 15,
    marginRight: 20,
    color: 'black',
    fontFamily: 'Mulish-Regular',
  },
  textType2: {
    fontSize: 20,
    marginTop: 15,
    marginLeft: 15,
    marginRight: 20,
    color: 'grey',
    fontFamily: 'Mulish-Regular',
  },
  cardMain: {
    marginLeft: 80,
    marginTop: 50,
  },
  cardMovie: {
    padding: 20,
    marginTop: 30,
    backgroundColor: '#FFFFF',
    height: 300,
    width: 200,
    marginRight: 10,
    borderWidth: 1,
    borderColor: '#D6D8E7',
    borderRadius: 6,
    alignItems: 'center',
  },
  movie: {
    marginTop: 20,
    width: '60%',
    height: 200,
    resizeMode: 'stretch',
    marginBottom: 100,
    borderRadius: 10,
    borderWidth: 1,
  },
  form: {
    alignItems: 'center',
  },
  layoutMenu: {
    paddingTop: 50,
    flexDirection: 'row',
    justifyContent: 'flex-start',
    padding: 10,
  },
  synopsis: {
    paddingLeft: 10,
    marginBottom: 60,
  },
  inputset: {
    marginTop: 30,
    alignItems: 'center',
    marginBottom: 50,
  },
  sort: {
    marginTop: 30,
    width: '60%',
    backgroundColor: '#FFFFF',
  },
  sortDrop: {
    borderColor: 'grey',
  },
  setdate: {
    marginTop: 30,
    width: 220,
    paddingTop: 10,
    paddingLeft: 10,
    borderWidth: 1,
    borderColor: 'black',
    height: 50,
    backgroundColor: 'white',
    borderRadius: 10,
  },
  setdatetext: {
    color: 'black',
  },
  input: {
    backgroundColor: 'white',
    width: '40%',
    borderWidth: 1,
    borderRadius: 10,
    paddingLeft: 30,
    marginBottom: 10,
  },
  scheduleCard: {
    marginTop: 20,
    marginBottom: 30,
    padding: 20,
    width: 300,
    height: 300,
    backgroundColor: '#FFFF',
    borderRadius: 20,
    alignItems: 'center',
  },
  sponsor: {
    width: '40%',
    height: 30,
    resizeMode: 'stretch',
  },
  scheduleText: {
    marginTop: 10,
    fontSize: 10,
    fontFamily: 'Mulish-Regular',
  },
  scheduleTime: {
    marginTop: 30,
    fontSize: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  scheduleTimeContent: {
    marginRight: 20,
    fontFamily: 'Mulish-Regular',
  },
  priceContent: {
    marginTop: 30,
    marginBottom: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  priceText: {
    marginRight: 90,
    fontFamily: 'Mulish-Regular',
  },
  priceText2: {
    fontWeight: 'bold',
    fontFamily: 'Mulish-Regular',
  },
  buttonCard: {
    backgroundColor: '#5F2EEA',
    width: '90%',
    height: 30,
    marginTop: 20,
    alignItems: 'center',
    paddingTop: 5,
    borderRadius: 10,
  },
  buttonText: {
    color: 'white',
    fontFamily: 'Mulish-Regular',
  },
});
