import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  logo: {
    marginTop: 20,
    marginLeft: 30,
  },
  header: {
    marginTop: 20,
    marginLeft: 30,
    fontSize: 20,
    color: 'black',
    fontFamily: 'Mulish-Bold',
  },
  text: {
    marginTop: 20,
    marginLeft: 30,
    marginRight: 30,
    fontSize: 20,
    color: '#8692A6',
    fontFamily: 'Mulish-Regular',
  },
  label: {
    marginTop: 30,
    marginLeft: 30,
    fontSize: 20,
    color: '#4E4B66',
    fontFamily: 'Mulish-Regular',
  },
  inputform: {
    marginTop: 20,
    marginLeft: 30,
    fontSize: 20,
    color: '#8692A6',
    borderWidth: 1,
    borderRadius: 5,
    borderColor: '#4E4B66',
    backgroundColor: '#ffff',
    width: '85%',
    height: 50,
    fontFamily: 'Mulish-Regular',
  },
  button: {
    backgroundColor: '#5F2EEA',
    borderRadius: 14,
    width: '85%',
    height: 40,
    marginTop: 30,
    marginLeft: 30,
    fontSize: 20,
    color: '#4E4B66',
    alignItems: 'center',
    paddingTop: 10,
  },
  buttonText: {
    color: '#ffff',
    fontFamily: 'Mulish-Regular',
  },
  textSet: {
    textAlign: 'center',
    flexDirection: 'row',
  },
  textOption: {
    alignContent: 'center',
    marginTop: 20,
    marginLeft: 30,
    fontSize: 15,
    color: 'black',
    flex: 3,
    fontFamily: 'Mulish-Regular',
  },
  directText: {
    alignContent: 'center',
    marginTop: 20,
    marginLeft: 30,
    flex: 2,
    fontFamily: 'Mulish-Regular',
  },
  textButton: {
    fontSize: 15,
    color: '#5F2EEA',
    marginBottom: 10,
    fontFamily: 'Mulish-Regular',
  },
});
