import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  textType1: {
    fontSize: 12,
    marginTop: 15,
    marginLeft: 15,
    color: 'grey',
    fontFamily: 'Mulish-Regular',
  },
  textType2: {
    fontSize: 20,
    marginTop: 15,
    marginLeft: 15,
    color: 'black',
    fontWeight: 'bold',
    fontFamily: 'Mulish-Regular',
  },
  textType3: {
    fontSize: 20,
    marginTop: 15,
    marginLeft: 15,
    marginRight: 100,
    color: 'black',
    fontWeight: 'bold',
    fontFamily: 'Mulish-Regular',
  },
  textType4: {
    fontSize: 20,
    marginTop: 15,
    marginLeft: 15,
    fontWeight: 'bold',
    fontFamily: 'Mulish-Regular',
    color: '#5F2EEA',
  },
  layoutMenuTicket: {
    backgroundColor: 'white',
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 10,
  },
  layoutMenuTotal: {
    borderWidth: 1,
    marginTop: 30,
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 10,
    marginBottom: 20,
  },
  cardTicket: {
    marginLeft: 20,
    marginTop: 30,
    paddingTop: 20,
    marginBottom: 5,
    height: 250,
    borderRadius: 10,
    backgroundColor: 'white',
    width: '90%',
    alignItems: 'center',
  },
  photo: {
    marginTop: 10,
    marginBottom: 20,
    width: 200,
    height: 200,
    resizeMode: 'stretch',
  },
  cardDetail: {
    marginLeft: 20,
    paddingTop: 20,
    marginBottom: 20,
    height: 450,
    borderRadius: 10,
    backgroundColor: 'white',
    width: '90%',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  textSpace: {
    width: 100,
  },
  textSpace2: {
    width: 170,
  },
  textSpace3: {
    width: 130,
  },
  textSpace4: {
    width: 50,
  },
});
