import {StyleSheet} from 'react-native';

export default StyleSheet.create({
  textHeader: {
    fontSize: 20,
    marginTop: 15,
    marginLeft: 15,
    color: 'black',
    fontFamily: 'Mulish-Bold',
  },
  textType1: {
    fontSize: 20,
    marginTop: 15,
    marginLeft: 15,
    color: 'black',
    fontFamily: 'Mulish-Regular',
  },
  textType2: {
    fontSize: 20,
    marginTop: 15,
    marginLeft: 15,
    color: 'grey',
    fontFamily: 'Mulish-Regular',
  },
  textType3: {
    textAlign: 'left',
    fontSize: 14,
    marginTop: 15,
    marginLeft: 15,
    color: 'grey',
    fontFamily: 'Mulish-Regular',
  },
  layoutMenuPayment: {
    backgroundColor: 'white',
    flexDirection: 'row',
    justifyContent: 'space-between',
    padding: 10,
  },
  cardPayment: {
    marginLeft: 20,
    marginTop: 30,
    marginBottom: 50,
    height: 300,
    borderRadius: 10,
    backgroundColor: 'white',
    width: '90%',
    alignItems: 'center',
  },
  paymentMethod: {
    marginTop: 30,
    fontSize: 10,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  paymentContent: {
    marginRight: 20,
    width: 70,
    height: 40,
    borderWidth: 1,
    borderRadius: 10,
    borderColor: 'grey',
    padding: 7,
  },
  paymentImage: {
    width: 50,
    height: 20,
    resizeMode: 'stretch',
  },
  textSet: {
    textAlign: 'center',
    flexDirection: 'row',
    fontFamily: 'Mulish-Regular',
  },
  textOption: {
    alignContent: 'center',
    marginTop: 50,
    marginLeft: 30,
    fontSize: 15,
    color: 'black',
    flex: 3,
    fontFamily: 'Mulish-Regular',
  },
  directText: {
    alignContent: 'center',
    marginTop: 50,
    marginLeft: -100,
    flex: 2,
    fontFamily: 'Mulish-Regular',
  },
  textButtonDirect: {
    fontSize: 15,
    color: '#5F2EEA',
    marginBottom: 10,
    fontFamily: 'Mulish-Regular',
  },
  cardPersonal: {
    marginLeft: 20,
    marginTop: 30,
    marginBottom: 50,
    height: 400,
    borderRadius: 10,
    backgroundColor: 'white',
    width: '90%',
    alignItems: 'center',
  },
  input: {
    marginTop: 10,
    paddingLeft: 30,
    width: '90%',
    borderWidth: 1,
    height: 40,
    borderRadius: 8,
  },
  warning: {
    alignItems: 'center',
    width: '90%',
    backgroundColor: '#F4B740',
    height: 40,
    marginTop: 50,
    borderRadius: 20,
    padding: 10,
  },
  textWarning: {
    color: 'grey',
    fontFamily: 'Mulish-Regular',
  },
  button: {
    width: '90%',
    backgroundColor: '#5F2EEA',
    marginLeft: 20,
    height: 50,
    paddingTop: 10,
    alignItems: 'center',
    marginBottom: 50,
    borderRadius: 15,
  },
  textButton: {
    color: 'white',
    fontFamily: 'Mulish-Regular',
  },
});
